[package]
name = "Logram"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # 指定生成动态链接库

[dependencies]
regex = "1"
fancy-regex = "0.8"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
md-5 = "0.10"