[package]
name = "Drain"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
fancy-regex = "0.8"
polars = "0.23" 
serde = { version = "1", features = ["derive"] }
csv = "1.1"
serde_json = "1.0"
md-5 = "0.10"
